### ISSUE TITLE
[GDPR08] Configure the minors and adults minimum age

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#1]
Reference: GDPR08 

**Is your feature request related to a problem? Please describe.**
As an implementer, a person that administers a Decidim application as a sysadmin, I want to be able to enable and configure the creation of minor accounts.
 
**Describe the solution you'd like**
As an implementer of Decidim, I would like to have an option in the system panel, that is, for each of the instances, where I can enable the creation of accounts by minors participants and other new functionalities related to this EPIC.

I should also be able to configure:

- from what age it is allowed to create these accounts (`minimum_minor_age`). The default would be 10 years. 
- from what age parental consent should no longer be requested. The default would be 14 years. (`minimum_adult_age`)

These two values (minimum age to create a minor account and age without parental consent), will be independently selectable when allowing access to a space. [ref: GDPR16].

Since the access of minors depends on the context of each organization, this development must be a module (Minors participation module)

**Describe alternatives you've considered**

To have it configurable through the initializer/secrets.yml/environment variables as other Decidim's settings, but these could depend on an Organization (aka Tenant), so it's better to have this kind of granularity.

**Does this issue could impact on users private data?**
Yes as it afects to minors data, it is particulary sensitive. 

**Acceptance criteria:**
- [x]  As an administrator of system I see the option of enable minor participation, only if minor module is installed
- [x] As an administrator of system I can enable the creation of minor accounts in a given Organization through /system panel
- [x] As an administrator of system I can specify the minimum age to create a minor account (`minimum_minor_age`) in a given Organization through /system panel
- [x] As an administrator of system I can specify the legal age of consent to create a minor account without parental permission (`minimum_adult_age`) in a given Organization through /system panel

**Comment by paarals** [comment]
hi @NilHomedes, we are thinking something like that:
![imatge](https://user-images.githubusercontent.com/40388743/194849143-90570cae-e9c7-4aba-a828-585daa1be990.png)

- [ ] As an administrator of system I see the option of enable minor participation, only if minor module is installed 
- [ ] As an administrator of system I can enable minor participation or not for each space (tenant)
- [ ] As an administrator of system I can set minimum_minor_age and minimum_adult_age for each space (tenant)

also, texts must be reviewed

**Comment by NilHomedes** [comment]
The prototype looks good to me Pau!

**Comment by NilHomedes** [comment]
Everything looks good in production. 

Just one comment, we think that the minors account setting should be under "Show advanced settings". In order to be consistent with https://github.com/decidim/decidim/issues/7728

**Comment by paarals** [comment]
in which position @NilHomedes? first one? last one? in the middle?

**Comment by NilHomedes** [comment]
I would say first one

**Comment by microstudi** [comment]
@NilHomedes advances settings applied in staging.
