### ISSUE TITLE
[GDPR 11] Promote minor account to adult account

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#20]
Ref: GDPR 11

**Is your feature request related to a problem? Please describe.**
As a registered user with a minor account, I want to be able to promote my account when I have reached the legal age of consent for data protection purposes, to have an adult (regular) account.

**Describe the solution you'd like**
When the minor reaches the age of majority, an email will be sent to the minor and the guardian to let them know that their accounts are now independent.

This task will be executed automatically when the minor exceeds the age from which the guardian's authorisation is no longer required (ref: GDPR09).

**Describe alternatives you've considered**
Another possibility would be that the minor is the one who directly promotes his or her account to the adult.

This implies thinking about what happens if the minor does not do this promotion. This would require us to perform an automatic task once a year to automatically promote the accounts of minors who are over the maximum age.

As the access for minors depends on the context of each organisation, this development should be a module.

**Does this issue could impact on users private data?**
Yes as it afects to minors data, it is particulary sensitive.

**Acceptance criteria**

- [ ] As a registered minor when I reach the legal age of consent my account is automatically promoted to adult.
- [ ] As a registered minor when I reach the legal age of consent I receive an email stating that my account has been promoted to adult.

**Comment by fblupi** [comment]
@NilHomedes could you provide us the default subject and content of the email that the user must receive when the account is promoted?

**Comment by NilHomedes** [comment]
It could be like this:

Hi {%user}, your account has been promoted. You now have an adult account and your account is no longer dependent on your legal guardian's account.
