### ISSUE TITLE
[GDPR 16] Space with access for minors

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#22]
Ref: GDPR 16

**Is your feature request related to a problem? Please describe.**
In some processes, children of different ages may coexist. For example, in a class group, children of 13 and 14 years of age can coexist. Therefore, as an administrator, you should be able to define that an exclusive space for minors can also include minors who are above the legal age of consent established in the system.

As well as teachers or adults with special permissions

**Describe the solution you'd like**
As an administrator I would like to be able to set various degrees of access depending on the type of process to be carried out and the age of the participants:
- Space for all. All participants will have access regardless of the age of the participants.
- Exclusive space for minors:
     - For minors with guardianship, who are participants below the legal age of consent `minimum_minor_age`. According to what has been configured in the system "Enable the option to have accounts for minors" - ref: [GDPR08]).
     - Have the option to limit that minors without guardianship can participate. I.e. who are above the `minimum_adult_age`, but below the age of majority (Ref: GDPR 18).

- They will also be able to access:
     - facilitators of the participation space (with existing profiles of administrators, collaborators, moderators).
     - tutors associated with minors, with read-only access.
     - ~~new read-only role without access to the administration panel, by educators or similar figures. See ref: [GDPR17].~~
     - those participants who have been verified with the municipal register in case this option is activated. See ref: [GDPR18]
    
- Visitors and other participants who do not comply with the rules will not have access, but will be able to view the space. When they click on it, they will see an error message "you cannot access this space because you do not meet the requirements".
- The space will be accessible but its contents will not be visible by transversal functionalities (e.g. the search engine, profile follow sections, GraphQL API, etc).

**Describe alternatives you've considered**
Ideas are welcome

**Does this issue could impact on users private data?**
Yes as it afects to minors data, it is particulary sensitive.

**Acceptance criteria**

- [x] As an admin, I can create a participatory space (process or assembly) exclusive for minors in guardianship. 
- [x] As an admin, I can define if I allow minors without guardianship to participate in a participatory space exclusive for minors.
- [x] As a minor in guardianship, I can acces to a participatory space exclusive for minors.
- [x] As a minor without guardianship, I can participate in a participatory space exclusive for minors, when it's able to me. 
- [x] As a visitor or participant I can see the participatory space but I can not access to it. I see an error message when I click on it.
- [x] As a visitor or a participant, I am not able to find the content generated in a participatory space exclusive for minors in any of the transversl funcionalities (the search engine, profile follow sections, GraphQL API, etc).

**Comment by microstudi** [comment]
https://github.com/AjuntamentdeBarcelona/decidim-module-kids/pull/36
