### ISSUE TITLE
[GDPR13] Activiy log for minors

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#4]
Reference: GDPR13

**Is your feature request related to a problem? Please describe.**
As an implementer of a installation, I would like to have a log file that is separate or with a particular prefix that allows me to more easily access actions related to minors.

**Describe the solution you'd like**
The log file could be for example:
- log/production-minor-consent.log or the prefix MINOR-CONSENT inside of the file log/production.log
- log/production-minor-activity.log or the prefix MINOR-ACTIVITY inside of the file log/production.log

As the access for minors depends on the context of each organisation, this development should be a module

**Does this issue could impact on users private data?**
Yes as it afects to minors data, it is particulary sensitive.

**Acceptance criteria**
- [ ] As an implementer I can have a separate log file for the minors activity

**Comment by fblupi** [comment]
@NilHomedes what's the difference between minor consent and minor activity?

**Comment by NilHomedes** [comment]
I understand that "consent" refers to the action of creating a minor user, made by a legal guardian. And "Activity" is the activity of the minor itself.

**Comment by fblupi** [comment]
In that case, I need [this PR](https://github.com/AjuntamentdeBarcelona/decidim-module-kids/pull/27) to be finished and merged to finish it.
