### ISSUE TITLE
[GDPR10] Log in as a minor

### ISSUE THREAD

**Issue by NilHomedes** [AjuntamentdeBarcelona/decidim-module-kids#5]
Reference: GDPR10

**Is your feature request related to a problem? Please describe.**
As a minor, once my account has been created for me by my guardian (see "Associated account for minors", ref: GDPR09), I would like to be able to log in.

**Describe the solution you'd like**
As a minor, I would like to log in with my e-mail address and password.

I would like to change my user password. As this user I will have access to minors spaces (see "Spaces with access by minors", ref: GDPR16).

As the access for minors depends on the context of each organisation, this development must be a module

**Describe alternatives you've considered**
Have an exclusive login path for minors.

**Does this issue could impact on users private data?**
Yes as it afects to minors data, it is particulary sensitive. 

**Acceptance criteria**
- [x] As a minor registered I can be able to log in
- [x] As a minor registered I can be able to change my password
- [x] As a minor registered I can be able to change my profile data, except for my birthday
- [x] As a minor registered, I can only receive private messages from other underage users.
- [x] As a minor registered I can't be able to access to authorizations page

**Comment by fblupi** [comment]
As we reviewed in the last meeting, the acceptance criteria for this issue should be changed. I see ok the first three points, but the last one can't be done still as there are no "minors spaces" yet.

We should add new acceptance criteria: "As a minor registered I can't be able to access to authorizations page".

**Comment by NilHomedes** [comment]
Now it's updated! 
I add another AC, we've been discussing it with Arnau, and we think it's necessary to protect minors. If you need to, we can discuss it further.

**Comment by fblupi** [comment]
Yes, the one about private messages. I'll try to have this done by the end of this sprint. But I can't confirm it as this issue was estimated without it.

**Comment by fblupi** [comment]
I created a draft with PR #30. It contains all acceptance criteria except the one about the message restriction.

I also need to add tests to the PR, but the work is almost finished.
